// Generated by CoffeeScript 1.6.3
jQuery(document).ready(function($) {
  var featherEditor, _vals;
  _vals = MicrostockPhotoPlugin_aviary_script;
  return featherEditor = new Aviary.Feather({
    apiKey: _vals.api_key,
    apiVersion: 3,
    theme: 'light',
    postUrl: _vals.ajax_url,
    onLoad: function() {
      return $('input[name=mpp_edit_button]').live('click', function() {
        var $loader, $t;
        $t = $(this);
        $loader = $t.parent().find('.mpp_edit_button_loader');
        $loader.css('display', 'inline');
        return $.post(MicrostockPhotoPlugin.ajax_url, {
          'a': 'getToken',
          'id': $t.attr('data-id')
        }, function(r) {
          var $mp, img, token, url;
          $loader.hide();
          if (r.token == null) {
            return false;
          }
          token = r.token;
          $mp = $('#mpp_edit_image');
          if ($mp.length > 0) {
            $mp.remove();
          }
          url = $t.attr('data-url');
          img = $('<img id="mpp_edit_image" style="display: none;" />');
          img.attr('src', url);
          img.appendTo('body');
          return featherEditor.launch({
            image: 'mpp_edit_image',
            url: url,
            postData: token,
            onSave: function(imageID, newURL) {
              var checkToken;
              $loader.css('display', 'inline');
              checkToken = function() {
                return $.post(MicrostockPhotoPlugin.ajax_url, {
                  'a': 'checkToken',
                  'token': token
                }, function(r) {
                  if (r.status === -1) {
                    $loader.hide();
                    return false;
                  } else if (r.status === 0) {
                    return window.setTimeout(function() {
                      return checkToken();
                    }, 1000);
                  } else if (r.status === 1 && (r.id != null)) {
                    $loader.hide();
                    return window.mpp_selectImage(r.id);
                  }
                }).error(function() {
                  $loader.hide();
                  return alert(MicrostockPhotoPlugin.text.ajax_error);
                });
              };
              return checkToken();
            }
          });
        }).error(function() {
          $loader.hide();
          return alert(MicrostockPhotoPlugin.text.ajax_error);
        });
      });
    }
  });
});
